# Generated by Django 2.2 on 2021-06-23 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Phoneno',
            field=models.BigIntegerField(default=0),
        ),
    ]
