# Generated by Django 2.2 on 2021-06-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_app', '0002_register_phoneno'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='Add',
            field=models.CharField(default='', max_length=50),
        ),
    ]
