# Generated by Django 2.2 on 2021-06-25 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_app', '0004_register_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='register',
            old_name='image',
            new_name='Image',
        ),
    ]
