# Generated by Django 2.2 on 2021-06-26 06:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_app', '0005_auto_20210625_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='Image',
            field=models.ImageField(default='avtar.png', upload_to='images/'),
        ),
    ]
