# Generated by Django 2.2 on 2021-07-08 09:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_app', '0008_kitchen_image'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Kitchen_Image',
            new_name='Images',
        ),
        migrations.RenameField(
            model_name='images',
            old_name='Image',
            new_name='Kitchen_Image',
        ),
    ]
