# Generated by Django 2.2 on 2021-07-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_app', '0010_auto_20210708_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='Kitchen_Image',
            field=models.ImageField(default='', upload_to='images/'),
        ),
    ]
