# Generated by Django 2.2 on 2021-07-10 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('furniture_app', '0015_auto_20210710_1044'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kitchen_Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Kitchen_Image', models.ImageField(blank=True, default='', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Pvcdoor_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pvcdoor_Image', models.ImageField(blank=True, default='', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Pvcparition_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Pvcparition_Image', models.ImageField(blank=True, default='', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Tvcabinet_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tvcabinet_Image', models.ImageField(blank=True, default='', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Upvcwindow_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Upvcwindow_Image', models.ImageField(blank=True, default='', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Wallpanelling_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wallpanelling_Image', models.ImageField(blank=True, default='', upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Wardrobe_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Wardrobe_Image', models.ImageField(blank=True, default='', upload_to='images/')),
            ],
        ),
        migrations.RenameModel(
            old_name='Images',
            new_name='Designerceiling_Image',
        ),
        migrations.RenameField(
            model_name='designerceiling_image',
            old_name='Kitchen_Image',
            new_name='Designerceiling_Image',
        ),
    ]
